# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: midl-app
  RUN_REGION: us-central1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  DB_API_KEY: ${{ secrets.API_KEY }}
  DB_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  DB_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  DB_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
  DB_MSG_SENDER_ID: ${{ secrets.MSG_SENDER_ID }}
  DB_APP_ID: ${{ secrets.APP_ID }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
  
      # Build and push image to Google Container Registry
      - name: Build and Push Image
        run: |
          gcloud auth configure-docker -q
          docker build --build-arg API_KEY=$DB_API_KEY --build-arg AUTH_DOMAIN=$DB_AUTH_DOMAIN --build-arg PROJECT_ID=$DB_PROJECT_ID --build-arg STORAGE_BUCKET=$DB_STORAGE_BUCKET --build-arg MSG_SENDER_ID=$DB_MSG_SENDER_ID --build-arg APP_ID=$DB_APP_ID -t gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated
